version: '2'
services:
    furyviewer-app:
        image: furyviewer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://furyviewer-mysql:3306/furyviewer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    furyviewer-mysql:
        extends:
            file: mysql.yml
            service: furyviewer-mysql
